---
- name: Create kafka default folder
  file:
    path: /opt/kafka
    owner: kafka
    group: kafka
    state: directory
    mode: 0750

- name: Unpack kafka tarball file
  unarchive:
    src: "{{ kafka_binaries }}"
    dest: /opt/kafka
    owner: kafka
    group: kafka
    remote_src: yes
    extra_opts: [--strip-components=1]
    keep_newer: yes

