---
- name: Create zookeeper group
  group: 
    name: zookeeper
    state: present
    system: yes

- name: Create zookeeper user
  user: 
    name: zookeeper
    group: zookeeper
    comment: "Zookeeper default user"
    shell: /bin/bash
    system: yes
