---
- name: Unpack zookeeper tarball file
  unarchive:
    src: zookeeper-{{zookeeper_version}}.tar.gz
    dest: /opt/
    creates: /opt/zookeeper-{{zookeeper_version}}
    owner: zookeeper
    group: zookeeper
    keep_newer: yes

- name: Create link pointing to the current installation
  file:
    src: /opt/zookeeper-{{zookeeper_version}}
    dest: /opt/zookeeper
    owner: zookeeper
    group: zookeeper
    state: link
